# Generated by Django 5.0.7 on 2024-07-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='price',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
