# Generated by Django 5.0.7 on 2024-07-16 14:18
from django.db import migrations, transaction
from django.apps.registry import Apps
from datetime import datetime


class Migration(migrations.Migration):

    def populate_orders(apps: Apps, _):

        order_model = apps.get_model("api", "OrderModel")
        carrier = apps.get_model("api", "CarrierModel")

        addresses = [
            [
                "Street 1, 10115 Berlin, Germany",
                "Street 10, 75001 Paris, France",
                "Street 3, 80331 Munich, Germany",
            ],
            [   "Street 5, 28013 Madrid, Spain", 
                "Street 2, 20144 Hamburg, Germany",
                "Street 5, 28013 Madrid, Spain"
            ],
        ]

        orders = [
                order_model(
                    sender=addresses[0][0],
                    receiver=addresses[0][1],
                    scheduled_for=datetime.now(),
                    status="in-transit",
                    carrier = carrier.objects.get(name="DHL"),
                    tracking_number = "TN12345678"
                ),
                order_model(
                    sender=addresses[1][0],
                    receiver=addresses[1][1],
                    scheduled_for=datetime.now(),
                    status="inbound-scan",
                    carrier = carrier.objects.get(name="UPS"),
                    tracking_number = "TN12345679"
                ),
                order_model(
                    sender=addresses[0][2],
                    receiver=addresses[1][2],
                    scheduled_for=datetime.now(),
                    status="delivery",
                    carrier = carrier.objects.get(name="DPD"),
                    tracking_number = "TN12345680"
                ),
                

        ]
        with transaction.atomic():
            order_model.objects.bulk_create(orders)
    
    def delete_orders(apps: Apps, _):
        order_model = apps.get_model("api", "OrderModel")
        order_model.objects.all().delete()


    dependencies = [
        ("api", "0003_auto_20240716_1415"),
    ]

    operations = [migrations.RunPython(populate_orders, delete_orders)]
