# Generated by Django 5.0.7 on 2024-07-16 14:38

from django.db import migrations, transaction
from django.apps.registry import Apps
from datetime import datetime


class Migration(migrations.Migration):

    def populate_order_items(apps: Apps, _):

        order_item = apps.get_model("api", "OrderItem")
        article = apps.get_model("api", "ArticleModel")
        order_model = apps.get_model("api", "OrderModel")


        ordersitems = [
                
                order_item(
                articles = article.objects.get(sku="LP123"),
                quantity = 1,
                order = order_model.objects.get(tracking_number = "TN12345678")),
                
                order_item(
                articles = article.objects.get(sku="MO456"),
                quantity = 1,
                order = order_model.objects.get(tracking_number = "TN12345678")),
                
                order_item(
                articles = article.objects.get(sku="MT789"),
                quantity = 1,
                order = order_model.objects.get(tracking_number = "TN12345679")),
                
                order_item(
                articles = article.objects.get(sku="KB012"),
                quantity = 1,
                order = order_model.objects.get(tracking_number = "TN12345680")),
                
                order_item(
                articles = article.objects.get(sku="MO456"),
                quantity = 1,
                order = order_model.objects.get(tracking_number = "TN12345680")),
                
        ]
        with transaction.atomic():
            order_item.objects.bulk_create(ordersitems)
    
    def delete_orders_items(apps: Apps, _):
        order_item = apps.get_model("api", "OrderItem")
        order_item.objects.all().delete()

    dependencies = [
        ('api', '0004_auto_20240716_1418'),
    ]

    operations = [
        migrations.RunPython(populate_order_items, delete_orders_items)
    ]
